Enable Partial and Node rendering
psmb/Psmb.Newsletter pull request #1
Opened 2017-01-09 15:21 UTC by Snejmann

I also think it's useful to render **text/html** and **text/plain** in one part. Just check FusionMailService.php

2017-01-13 16:02 UTC, dimaip requested changes
Hey, thanks a lot for your work! Just a few comments from me.

2017-01-13 16:02 UTC, dimaip commented on Classes/Psmb/Newsletter/Service/FusionMailService.php
> +        $mail->setBody(Html2Text::convert($body), 'text/plain');
Do you think it would be a able to convert rich html to plain text reasonably accurate? I need to think about this a bit more.

2017-01-13 16:02 UTC, dimaip commented on Classes/Psmb/Newsletter/Service/FusionMailService.php
>              'documentNode' => $siteNode,
You probably would want to change the `documentNode` as well?

2017-01-13 16:02 UTC, dimaip commented on composer.json
> +        "soundasleep/html2text": "~0.3"
Why did you choose this particular converter? Did you consider alternatives, is this the best one?

2017-01-13 16:02 UTC, dimaip commented on Classes/Psmb/Newsletter/Command/NewsletterCommandController.php
> +        $actionRequest->setFormat('html');
I already fixed this here https://github.com/psmb/Psmb.Newsletter/commit/a1bb6231fec1f0a0920f35c0512a3d133a1a6c00
The way you did it is a bit cleaner. If you want, you can rebase the change and remove my fix and leave yours.

2017-01-18 15:41 UTC, Snejmann commented on composer.json
> +        "soundasleep/html2text": "~0.3"
It's open source and there are current commits.

2017-01-18 15:42 UTC, Snejmann commented on Classes/Psmb/Newsletter/Command/NewsletterCommandController.php
> +        $actionRequest->setFormat('html');
I think it looks good though

2017-01-18 15:43 UTC, Snejmann commented on Classes/Psmb/Newsletter/Service/FusionMailService.php
> +        $mail->setBody(Html2Text::convert($body), 'text/plain');
I think so, but maybe we should do some tests on it?

2017-01-18 15:46 UTC, jensschuett commented on Classes/Psmb/Newsletter/Service/FusionMailService.php
>              'documentNode' => $siteNode,
Yes of course, can you add it to the code?

2017-03-20 13:56 UTC, closed without merging